logistic_regression:
  max_iter: [500]
  C: [1]
  random_state: 42

decision_tree:
  max_depth: [10]
  min_samples_split: [5]
  random_state: 42

random_forest:
  n_estimators: [100]
  max_depth: [15]
  random_state: 42

gradient_boosting:
  n_estimators: [100]
  learning_rate: [0.1]
  max_depth: [3]
  random_state: 42

xgboost:
  n_estimators: [100]
  learning_rate: [0.1]
  max_depth: [3]
  random_state: 42
  tree_method: 'hist'

lightgbm:
  n_estimators: [100]
  learning_rate: [0.1]
  num_leaves: [31]
  random_state: 42

cv_splits: 2
random_state: 42



